[pose]
L-Wrist = 166.19
R-Wrist = 145.01
L-Elbow = 75.73
R-Elbow = 146.74
L-Arm-Open = 25.52
R-Arm-Open = 40.11
L-Knee = 69.08
R-Knee = 96.54
L-Hip-Open = 50.14
R-Hip-Open = 100.24
Bend-Forward = 50.14
Spine-Alignment = 168.68
L-Ankle = 168.38
R-Ankle = 160.75
