yoga_name = "Utkatasana"

[description]
context = "The Chair Pose is a strengthening and heat-building asana that brings all parts of your body together into a cohesive and powerful whole. A deep squat, this pose immediately engages the strength of your legs, back, and ankles. It helps to build endurance and grounding."
howto = """Chair Pose:
1. Stand in Chair Pose with big toes touching and heels slightly apart.
2. Raise your arms overhead so that your biceps are just slightly in front of your ears. Keep your arms parallel, palms facing inward.
3. Bend your knees, sitting your hips back and down as if sitting into an imaginary chair.
4. Shift your weight into your heels so you can lift your toes slightly.
5. Keep your lower back long (avoid overarching) by drawing your lower belly in and up.
6. Hold the pose, keeping the chest lifted and thighs parallel to the floor if possible."""

# """
# Exhale and bend your knees so that your thighs are as parallel to the floor as possible. Your knees will project out over your feet, and your trunk will lean slightly forward over your thighs until your front torso forms approximately a right angle with the tops of your thighs.
# Keep your inner thighs parallel to each other and press the heads of the thigh bones down toward your heels.
# Firm your shoulder blades against your back. Direct your tailbone down toward the floor and in toward your pubis to keep your lower back long.
# Stay for 30 seconds to a minute. To come out of this pose, straighten your knees with an inhalation, lifting strongly through your arms. Exhale and release your arms to your sides into Tadasana.
# """

[pose]
"Right Wrist" = 157.93
"Left Wrist" = 150.7
"Right Elbow" = 165.63
"Left Elbow" = 169.81
"Right Shoulder" = 62.92
"Left Shoulder" = 114.3
"Right Knee" = 111.61
"Left Knee" = 106.16
"Right Hip" = 61.98
"Left Hip" = 109.19
Spine = 61.98
"Spine Alignment" = 144.96
"Right Ankle" = 93.28
"Left Ankle" = 86.35

[marty]
LeftHip = 50
LeftTwist = 0
LeftKnee = 0
RightHip = 50
RightTwist = 0
RightKnee = 0
LeftArm = 150
RightArm = 150
Eyes = 0
