yoga_name = "Utkatasana"

[description]
context = "The Chair Pose (Utkatasana) is strengthening and heat-building and brings all parts of your body together into a cohesive and powerful whole. A deep squat, this pose immediately engages the strength of your legs, back, and ankles. It helps to build endurance and grounding."
howto = """(Chair Pose) From a standing position, the feet are together and rooted into the earth with toes actively lifted. The knees are bent and the weight of the body is on the heels of the feet. The pelvis is tucked in and the ribcage is lifted. The neck is a natural extension of the spine. The arms are lifted up toward the sky with the elbows straight and the biceps by the ears. The hands can be together or separated and facing each other with the fingers spread wide. The gaze is forward."""

# """
# Exhale and bend your knees so that your thighs are as parallel to the floor as possible. Your knees will project out over your feet, and your trunk will lean slightly forward over your thighs until your front torso forms approximately a right angle with the tops of your thighs.
# Keep your inner thighs parallel to each other and press the heads of the thigh bones down toward your heels.
# Firm your shoulder blades against your back. Direct your tailbone down toward the floor and in toward your pubis to keep your lower back long.
# Stay for 30 seconds to a minute. To come out of this pose, straighten your knees with an inhalation, lifting strongly through your arms. Exhale and release your arms to your sides into Tadasana.
# """

[pose]
"Right Wrist" = 175.09
"Left Wrist" = 158.73
"Right Elbow" = 175.47
"Left Elbow" = 174.66
"Right Shoulder" = 96.9
"Left Shoulder" = 100.59
"Right Knee" = 111.32
"Left Knee" = 126.21
"Right Hip" = 46.64
"Left Hip" = 114.99
Spine = 46.64
"Spine Alignment" = 168.98
"Right Ankle" = 101.34
"Left Ankle" = 123.22

[marty]
LeftHip = 50
LeftTwist = 0
LeftKnee = 0
RightHip = 50
RightTwist = 0
RightKnee = 0
LeftArm = 150
RightArm = 150
Eyes = 0
