model_path = "pose_landmarker_full.task"

[film_settings]
contrast = 1.2
brightness = -20
grain_intensity = 20
line_thickness = 5
head_radius_multiplier = 0.6

[colors]
skeleton_color = [255, 255, 255]
joint_dot_size = 2

[skeleton]
body_lines = [
    [11, 13], [13, 15], # Left Arm
    [12, 14], [14, 16], # Right Arm
    [23, 25], [25, 27], # Left Leg
    [24, 26], [26, 28]  # Right Leg
]

hand_lines = [
    [15, 19], # Left Hand
    [16, 20] # Right Hand
]

[feedback]
# Landmark indices for angle calculation [Start, Vertex, End]
joints_to_monitor = [
    { name = "L-Elbow", points = [11, 13, 15] },
    { name = "R-Elbow", points = [12, 14, 16] },
    { name = "L-Knee",  points = [23, 25, 27] },
    { name = "R-Knee",  points = [24, 26, 28] },
    { name = "L-Hip",   points = [11, 23, 25] },
    { name = "R-Hip",   points = [12, 24, 26] }
]
show_labels = true
text_scale = 0.5
max_error_margin = 60.0 # 0 deg = Green, 10+ deg = Red

[poses.test]
L-Elbow = 156
R-Elbow = 169
L-Knee = 146
R-Knee = 130
L-Hip = 167
R-Hip = 139
