yoga_name = "Tadasana"

[description]
context = "Mountain Pose is a foundational standing yoga posture used in Sun Salutations and as a base for other standing poses. While it appears to be simple standing, it actively strengthens the abdomen, back, and legs while stretching the entire body. When performed with proper alignment, it improves posture, develops balance, eases sciatica, and lifts the foot arches."
howto = "The body is in the standing position, with the feet together and rooted into the earth. The weight of the body is evenly distributed on the four corners of the feet. The pelvis is tucked. The ribcage is lifted. The neck is a natural extension of the spine and the chin is slightly tucked toward the sternum. The shoulders are relaxed as they rotate back and down. The arms at your sides. The gaze is forward."

[pose]
"Right Wrist" = 179.27
"Left Wrist" = 176.52
"Right Elbow" = 169.23
"Left Elbow" = 172.08
"Right Shoulder" = 4.52
"Left Shoulder" = 1.64
"Right Knee" = 179.36
"Left Knee" = 178.92
"Right Hip" = 100.0
"Left Hip" = 75.0
Spine = 47.2
"Spine Alignment" = 162.95
"Right Ankle" = 105.5
"Left Ankle" = 105.91

[marty]
LeftHip = 0
LeftTwist = 0
LeftKnee = 0
RightHip = 0
RightTwist = 0
RightKnee = 0
LeftArm = 0
RightArm = 0
Eyes = 0
