[pose]
L-Wrist = 164.27
R-Wrist = 170.17
L-Elbow = 46.92
R-Elbow = 157.15
L-Arm-Open = 31.05
R-Arm-Open = 34.23
L-Knee = 176.67
R-Knee = 178.59
L-Hip-Open = 86.92
R-Hip-Open = 88.64
Bend-Forward = 86.92
Spine-Alignment = 163.92
L-Ankle = 158.41
R-Ankle = 168.82
