yoga_name = "Virabhadrasana I"

[description]
context = "The right-side Warrior 1 (Virabhadrasana I) challenges balance and stability while engaging the stabilizing muscles of the right leg. It provides a deep stretch to the right psoas and hip flexor while building endurance in the triceps, quadriceps and calves."
howto = "From a standing position, the legs are in a wide stance with the feet aligned and flat on the earth. The left foot is in a 60-degree angle toward the front. The hips are squared. The inner thighs are rotated toward each other. The right knee is bent in a 90-degree angle directly above the ankle. The arms extend up to the sky with the biceps by the ears. The hands can be together or separated and facing each other with the fingers spread wide. The ribcage is lifted and the pelvis tucked. The gaze is forward."

[pose]
"Right Wrist" = 160.67
"Left Wrist" = 161.05
"Right Elbow" = 178.81
"Left Elbow" = 179.3
"Right Shoulder" = 61.84
"Left Shoulder" = 117.52
"Right Knee" = 167.69
"Left Knee" = 105.11
"Right Hip" = 132.41
"Left Hip" = 98.9
Spine = 132.41
"Spine Alignment" = 160.79
"Right Ankle" = 100.63
"Left Ankle" = 119.52

[marty]
LeftHip = -50
LeftTwist = 0
LeftKnee = 0
RightHip = 50
RightTwist = 0
RightKnee = 0
LeftArm = 150
RightArm = 150
Eyes = 0
