[pose]
L-Wrist = 178.53
R-Wrist = 178.27
L-Elbow = 152.71
R-Elbow = 167.28
L-Arm-Open = 23.88
R-Arm-Open = 24.56
L-Knee = 178.96
R-Knee = 178.02
L-Hip-Open = 89.16
R-Hip-Open = 89.22
Bend-Forward = 89.16
Spine-Alignment = 169.94
L-Ankle = 166.16
R-Ankle = 167.82

[marty]
LeftHip = 48
LeftTwist = 0
LeftKnee = -1
RightHip = 51
RightTwist = 0
RightKnee = 0
LeftArm = 0
RightArm = -1
Eyes = 0
