[pose]
L-Wrist = 165.17
R-Wrist = 153.54
L-Elbow = 62.01
R-Elbow = 128.92
L-Arm-Open = 54.96
R-Arm-Open = 39.35
L-Knee = 31.95
R-Knee = 20.03
L-Hip-Open = 6.11
R-Hip-Open = 88.64
Bend-Forward = 125.28
Spine-Alignment = 163.09
L-Ankle = 100.56
R-Ankle = 138.57
