[pose]
L-Wrist = 167.91
R-Wrist = 159.05
L-Elbow = 81.96
R-Elbow = 154.06
L-Arm-Open = 42.35
R-Arm-Open = 36.79
L-Knee = 140.58
R-Knee = 152.28
L-Hip-Open = 39.72
R-Hip-Open = 114.04
Bend-Forward = 39.72
Spine-Alignment = 156.43
L-Ankle = 169.43
R-Ankle = 152.95
