[description]
context = ""
howto = ""

[pose]
R-Wrist = 170.47
L-Wrist = 157.16
R-Elbow = 158.02
L-Elbow = 168.81
R-Shoulder = 14.26
L-Shoulder = 12.31
R-Knee = 178.67
L-Knee = 179.51
R-Hip = 95.61
L-Hip = 90.25
Spine = 90.25
Spine-Alignment = 177.49
R-Ankle = 173.49
L-Ankle = 179.9

[marty]
LeftHip = -53
LeftTwist = 5
LeftKnee = 1
RightHip = 54
RightTwist = 5
RightKnee = 7
LeftArm = 144
RightArm = 151
Eyes = 1
