[description]
context = ""
howto = ""

[pose]
R-Wrist = 177.06
L-Wrist = 157.77
R-Elbow = 132.69
L-Elbow = 52.88
R-Shoulder = 44.94
L-Shoulder = 1.23
R-Knee = 178.07
L-Knee = 179.77
R-Hip = 93.94
L-Hip = 82.71
Spine = 82.71
Spine-Alignment = 177.84
R-Ankle = 161.73
L-Ankle = 178.62

[marty]
LeftHip = -24
LeftTwist = -42
LeftKnee = -60
RightHip = 54
RightTwist = 0
RightKnee = -7
LeftArm = -65
RightArm = 100
Eyes = 0
