[pose]
L-Wrist = 177.88
R-Wrist = 178.18
L-Elbow = 173.23
R-Elbow = 175.44
L-Arm-Open = 68.38
R-Arm-Open = 119.1
L-Knee = 178.2
R-Knee = 123.05
L-Hip-Open = 115.99
R-Hip-Open = 107.84
Bend-Forward = 115.99
Spine-Alignment = 167.9
L-Ankle = 153.03
R-Ankle = 108.12

[marty]
LeftHip = 49
LeftTwist = 0
LeftKnee = 5
RightHip = -53
RightTwist = -1
RightKnee = -6
LeftArm = -66
RightArm = 100
Eyes = 0

