yoga_name = "Anjaneyasana"

[description]
context = "Crescent Moon (Anjaneyasana) pose deeply stretches and opens the sides of the body and improves core body strength, balance and concentration. Half moon strengthens the ankles and knees, improves circulation and energizes the entire body."
howto = "The body is in the standing position, with the feet together and rooted into the earth. The weight of the body is evenly distributed on the four corners of the feet. The pelvis is tucked. The ribcage is lifted. The neck is a natural extension of the spine and the chin is slightly tucked toward the sternum. The shoulders are relaxed as they rotate back and down. The arms at your sides. The arms are extend upwards toward the sky as you bend to one side, lengthening the opposite side of the rib cage and stretch."

[pose]
"Right Wrist" = 150.64
"Left Wrist" = 158.07
"Right Elbow" = 168.27
"Left Elbow" = 167.64
"Right Shoulder" = 126.44
"Left Shoulder" = 65.3
"Right Knee" = 178.49
"Left Knee" = 178.89
"Right Hip" = 100.0
"Left Hip" = 75.0
Spine = 65.85
"Spine Alignment" = 178.5
"Right Ankle" = 110.67
"Left Ankle" = 106.96

[marty]
LeftHip = 0
LeftTwist = 0
LeftKnee = 0
RightHip = 0
RightTwist = 0
RightKnee = 0
LeftArm = 150
RightArm = 150
Eyes = 0
