yoga_name = "Virabhadrasana II"

[description]
context = "Warrior 2 (Virabhadrasana II) is a powerful standing pose that increases stamina and strengthens the legs and ankles. It opens the hips and chest while stimulating abdominal organs. On the left side, it specifically targets the opening of the left hip and strengthening of the left quadricep."
howto = "From a standing position, the legs are separated into a wide stance. The left knee is bent in a 90-degree angle directly above the ankle. The right leg is extended and straight with the outside edge of the back foot gripping the earth in a 60-degree angle toward the front. The inner thighs are externally rotated away from each other. The pelvis is tucked. The ribcage is lifted. The arms are extended out to the sides and are aligned with the shoulders in a straight line with the fingers reaching out as the shoulder blades squeeze together. The gaze is toward the front fingers."


[pose]
"Right Wrist" = 176.21
"Left Wrist" = 173.47
"Right Elbow" = 174.19
"Left Elbow" = 179.37
"Right Shoulder" = 93.66
"Left Shoulder" = 95.43
"Right Knee" = 100.17
"Left Knee" = 170.25
"Right Hip" = 89.67
"Left Hip" = 121.19
Spine = 149.62
"Spine Alignment" = 167.69
"Right Ankle" = 122.08
"Left Ankle" = 96.52

[marty]
LeftHip = 50
LeftTwist = 0
LeftKnee = 0
RightHip = -50
RightTwist = 0
RightKnee = 0
LeftArm = 90
RightArm = -70
Eyes = 0
