[pose]
L-Wrist = 176.62
R-Wrist = 166.14
L-Elbow = 65.22
R-Elbow = 148.52
L-Arm-Open = 30.63
R-Arm-Open = 32.99
L-Knee = 157.43
R-Knee = 164.69
L-Hip-Open = 71.39
R-Hip-Open = 96.2
Bend-Forward = 71.39
Spine-Alignment = 160.24
L-Ankle = 151.63
R-Ankle = 175.69
